cli: add application skeleton and support for personal dictionary gathering
labcif/GBoard4A pull request #3
Opened 2021-03-29 23:52 UTC by ljmf00

Signed-off-by: Luís Ferreira <contact@lsferreira.net>

2021-03-30 02:35 UTC, iK4tsu approved these changes

2021-03-30 02:35 UTC, iK4tsu commented on source/app.d
> +	auto opt = Options();
no need to call the initializer here:
```d
Options opt;
```

2021-03-30 02:35 UTC, iK4tsu commented on source/app.d
> +	}
We should add a required option within the opt itself.

2021-03-30 02:35 UTC, iK4tsu commented on source/app.d
> +				stderr.writeln("Output folder specified doesn't exists!");
```d
stderr.writefln!"The ouput folder specified '%s' does not exist!"(opt.output);
```

2021-03-30 02:35 UTC, iK4tsu commented on source/app.d
> +			if(!exists(dirName(opt.output)))
Shouldn't this be checked before running the analyzer?

2021-03-30 02:35 UTC, iK4tsu commented on source/gboardforensics/analysis/datadir.d
> + * Returns: gathered analysis data
Split this with an empty line in between.

2021-03-30 02:35 UTC, iK4tsu commented on source/gboardforensics/analysis/datadir.d
> +	AnalysisData analysisData = AnalysisData();
ditto
```d
AnalysisData analysisData;
```

2021-03-30 02:35 UTC, iK4tsu commented on source/gboardforensics/analysis/datadir.d
> +	];
Instead of hardcoding the databases here, we could have a configuration file for easier access and then import the file at compile time.

2021-03-30 02:35 UTC, iK4tsu commented on source/gboardforensics/analysis/file.d
> +	}
We should add a contract here to check the validity of the path.

2021-03-30 02:35 UTC, iK4tsu commented on source/gboardforensics/analysis/file.d
> +	 * Returns: true if database has android_metadata table, false otherwise
ditto

2021-03-30 02:35 UTC, iK4tsu commented on source/gboardforensics/analysis/file.d
> +			AND name = 'android_metadata';")
Better add LOWER or UPPER functions when searching strings.

2021-03-30 02:35 UTC, iK4tsu commented on source/gboardforensics/analysis/file.d
> +			.array.length > 0;
We can do this lazy
```d
import std.typecons : Yes, No;
import std.algorithm : map;

...
.each((i, ref _) => i > 0 ? No.each : Yes.each) == No.each;
```

2021-03-30 02:35 UTC, iK4tsu commented on source/gboardforensics/analysis/file.d
> +	AnalysisData analysisData = AnalysisData();
ditto

2021-03-30 02:35 UTC, iK4tsu commented on source/gboardforensics/gatherers/dictionary.d
> +	}
ditto

2021-03-30 02:35 UTC, iK4tsu commented on source/gboardforensics/gatherers/dictionary.d
> +	 */
ditto

2021-03-30 02:35 UTC, iK4tsu commented on source/gboardforensics/analysis/file.d
> +			AND name = 'android_metadata';")
No need for `;`

2021-03-30 02:36 UTC, iK4tsu requested changes
Miss clicked approve

2021-03-30 20:27 UTC, ljmf00 commented on source/gboardforensics/analysis/datadir.d
> +	AnalysisData analysisData = AnalysisData();
I prefer that way, but I'll change.

2021-03-30 20:27 UTC, ljmf00 commented on source/gboardforensics/analysis/datadir.d
> + * Returns: gathered analysis data
Done

2021-03-30 20:27 UTC, ljmf00 commented on source/app.d
> +				stderr.writeln("Output folder specified doesn't exists!");
Done

2021-03-30 20:27 UTC, ljmf00 commented on source/app.d
> +			if(!exists(dirName(opt.output)))
I need to make an extra check for `opt.output` but it makes sense, in terms of the program flow. I changed it.

2021-03-31 18:49 UTC, iK4tsu requested changes

2021-03-31 18:49 UTC, iK4tsu commented on source/gboardforensics/analysis/file.d
> +		in(exists(path) && isFile(path))
As per the Dlang style:
> Put a space after in/out similar to if constraints

Also, you can have multiple `in` contracts. Totally preferential:
```d
in (path.exists())
in (path.isFile())
```

2021-03-31 18:49 UTC, iK4tsu commented on source/gboardforensics/analysis/file.d
> +		in(file.isOpen)
ditto

2021-03-31 18:49 UTC, iK4tsu commented on source/gboardforensics/analysis/file.d
> +			AND name = 'android_metadata'")
Missed `LOWER(name)`.

2021-03-31 18:49 UTC, iK4tsu commented on source/gboardforensics/gatherers/dictionary.d
> +		in(exists(path) && isFile(path))
ditto

2021-03-31 21:38 UTC, iK4tsu approved these changes

2021-03-31 22:03 UTC, merged