Enhance HTML report with support for other models and timeline chart
labcif/GBoard4A pull request #36
Opened 2021-06-07 01:54 UTC by ljmf00

* expression history
* clipboard
* translation history

Also refactored diet views for more comprehensive and readable
templating.

Signed-off-by: Luís Ferreira <contact@lsferreira.net>

2021-06-07 02:04 UTC, ljmf00 commented
:angry: Why heisenberg's...

2021-06-07 11:25 UTC, iK4tsu commented
force push to restart the CI

2021-06-10 23:06 UTC, iK4tsu requested changes

2021-06-10 23:06 UTC, iK4tsu commented on source/gboardforensics/gatherers/clipboard.d
> +				""
```suggestion
				"" AS content
```

2021-06-10 23:06 UTC, iK4tsu commented on source/gboardforensics/gatherers/clipboard.d
> +				""
This is way easier to understand what is the purpose of the field. I would advise you to also document it.

2021-06-10 23:06 UTC, iK4tsu commented on source/gboardforensics/gatherers/clipboard.d
> +					);
```suggestion
					auto documentPath = _clipboard.path
						.dirName
						.buildPath("..", "files", e.uri
							.findSplitAfter("content://")[1]
							.findSplitAfter("/")[1]
					);
```

2021-06-28 14:31 UTC, ljmf00 commented on source/gboardforensics/gatherers/clipboard.d
> +				""
Done

2021-06-28 14:33 UTC, ljmf00 commented on source/gboardforensics/gatherers/clipboard.d
> +					);
Done

2021-07-11 20:29 UTC, iK4tsu approved these changes

2021-07-11 21:07 UTC, merged